BEGIN;

DROP TABLE IF EXISTS "artists", "tracks", "scores";

CREATE TABLE "artists" (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name          TEXT NOT NULL,
  instrument    TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ
);

CREATE TABLE "tracks" (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title         TEXT NOT NULL,
  year          INTEGER NOT NULL,
  artist_id     INTEGER,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ
);

CREATE TABLE "scores" (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  file_name     TEXT NOT NULL,
  file_path     TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ
);

ALTER TABLE "tracks" ADD FOREIGN KEY (artist_id) REFERENCES artists (id) ON DELETE CASCADE;

COMMIT;